- src/docs/references/transaction-process-actions/index.md
Direct link to the action reference preview: https://deploy-preview-309--sharetribe-flex-docs-site.netlify.app/docs/references/transaction-process-actions/
> Add privileged-set-line-items action doc and deprecate others

- src/docs/background/privileged-transitions/index.md
- src/docs/references/transaction-process-actions/index.md
- src/docs/references/transaction-process-format/index.md
PR replaces #315.
This incorporates the changes from #319
> Documentation about transaction metadata and operator transitions via Integration API

- src/docs/references/email-templates/index.md
- static/sample-template-context.json
Adds tx metadata attribute to email templates reference.
Also, updates sample email context with tx protected data and metadata.
> Transaction metadata in transaction email templates

- src/docs/background/features/index.md
custom pricing -> pricing
Relates to: 
https://github.com/sharetribe/flex-docs/commit/443a935513b21c0f27e4f963f8490603f81ce773
https://github.com/sharetribe/flex-docs/pull/308
> Fix pricing link

- src/docs/cookbook-social-logins-and-sso/enable-facebook-login/index.md
- src/docs/flex-cli/edit-email-templates-with-flex-cli/index.md
- src/docs/flex-cli/edit-transaction-process-with-flex-cli/index.md
Small updates on Facebook login cookbook and Flex CLI articles.
> Misc updates

- src/docs/references/events/index.md
Suggestion to different structure inside this article. This way event formats are not discussed before they are defined.
So, main suggestion:
- Removing format discussion from `## Event data`
- Swapping the order of `### Event data formats` & `### Resource data and previous values`
- Moving the preassumptions of `### Resource data and previous values` to the beginning of the example
- Opening format examples a bit: first `...` > `// other event keys: "eventType", "sequenceId", "createdAt", "marketplaceId", "source", "resourceId", "resourceType", "auditData"`
- `### Event sources` > `## Event sources`
https://deploy-preview-369--sharetribe-flex-docs-site.netlify.app/docs/references/events/
> Events refactored structure

- src/config-site-structure.js
- src/docs/cookbook-events/reacting-to-events/index.md
- src/docs/flex-cli/view-events-with-flex-cli/index.md
- src/docs/ftw-search/how-to-use-google-maps-in-ftw/index.md
- src/docs/operator-guides/flex-operator-resources/index.md
- src/docs/references/events/index.md
- src/ui-texts.json
Based on #367 
Reading at: https://deploy-preview-370--sharetribe-flex-docs-site.netlify.app/docs/cookbook-events/reacting-to-events/
> Events cookbook

- src/docs/cookbook-social-logins-and-sso/setup-oidc-proxy/index.md
Add information about testing in Heroku because localhost won't work
> Update OIDC proxy doc

- src/components/GlobalStyle.js
- src/components/Sidebar/CategoryList.js
- src/components/Topbar/OffScreenToggle.js
- src/components/Topbar/Search.js
- src/config.js
- src/font-faces.css
This PR;
- Adds Circular font back to the Flex Docs 
- Improves sidebar's readability with darkened and bolded text
Before; 
After;
> install circular and fix the readability issue on the sidebar

- src/docs/cookbook-social-logins-and-sso/enable-open-id-connect-login/index.md
- src/docs/cookbook-social-logins-and-sso/setup-oidc-proxy/index.md
- src/docs/ftw-hosting/how-to-deploy-ftw-to-production/index.md
Fix/remove broken links to Passport.js strategies.
> Fix broken links

- src/docs/cookbook-design/customize-image-sizes/index.md
- src/docs/ftw-styling/how-to-add-static-pages-in-ftw/index.md
- src/docs/ftw-styling/how-to-improve-performance/index.md
- src/docs/tutorial-branding/add-faq-page/index.md
> Update articles related to code splitting changes

- src/docs/cookbook-social-logins-and-sso/setup-oidc-proxy/index.md
- Improve the documentation on generating RSA keys
- Update document structure
> Update OpenID Connect proxy cookbook

- src/docs/background/commissions-and-monetizing-your-platform/index.md
The subscription-based model section now up-to-date.
> Subscription-based model section update

- src/docs/tutorial-transaction-process/customize-pricing/index.md
Add a null check for current cleaning fee when rendering listing wizard.
> Improve price customization tutorial

- src/docs/introduction/is-flex-right-for-you/index.md
In Is Flex Right For You, there was a broken link.
> Fixed link to calendly call

- src/docs/ftw-introduction/01-how-to-customize-ftw/index.md
- src/docs/operator-guides/introducing-yogatime/index.md
- src/docs/operator-guides/migrating-from-outside-sharetribe/index.md
Updated wording and a broken link in how-to-customize-ftw. Also ran format-docs.
> Updated how-to-customize-ftw

- src/docs/flex-cli/getting-started-with-flex-cli/index.md
Minor update to Flex CLI page.
> Update flex cli docs

- src/docs/ftw-introduction/ftw-hourly/index.md
- src/docs/operator-guides/migrating-from-outside-sharetribe/index.md
Leave out the possibility of upsert operation in intermediary article as the functionality has not been developed yet.
> Remote upsert operation mention from intermediary documentation

- src/components/BaseLayout.js
https://www.flowdock.com/app/kassi/support/threads/6FYs68griBAL4MVBbtzDoGIgW-u
> added trailing slash to canonicalisation

- src/docs/introduction/getting-started-with-ftw-daily/index.md
- src/docs/operator-guides/introducing-sneakertime/index.md
- src/docs/references/api-reference/index.md
> Update some links

- src/docs/tutorial-transaction-process/create-transaction-process/index.md
- src/docs/tutorial-transaction-process/customize-pricing/index.md
- Add an info box to pricing customization tutorial on updating new line item to email template
- Add an info box to booking unit type tutorial on updating type of line item to email template
> Add mentions about email template modifications in tutorial

- src/components/LandingPage/LandingPage.js
> Update outdated link

- src/components/ArticleIndexPage/ArticleIndex.js
- src/pages/concepts.js
- src/pages/design-toolkit.js
- src/pages/ftw.js
- src/pages/how-to.js
- src/pages/introduction.js
- src/pages/operator-guides.js
- src/pages/references.js
- src/pages/tutorial.js
Fixes missing trailing slashes on category pages
> fix issue with trailing slash

- src/config-site-structure.js
Reorder the articles in FTW Introduction section to improve reading flow
> Reorder FTW-introduction articles for clarity

- .husky/pre-commit
- .lintstagedrc
- package.json
- yarn.lock
Add pre-stage commit that runs prettify on staged files
> Pre commit prettify

- src/docs/howto-migrations/migrating-from-outside-sharetribe/index.md
Sync both migration instructions to describe when to request a migration and how
> Add instructions to request 3rd party migration

- src/docs/ftw-configuration/how-to-set-up-currency-in-ftw/index.md
Add IC-macro on multiple currencies as paragraph in the FTW currencies article
> Add chapter on FTW and multiple currencies

- src/docs/concepts-extended-data/extended-data-introduction/index.md
- src/docs/concepts-extended-data/listing-extended-data/index.md
- src/docs/concepts-extended-data/transaction-extended-data/index.md
- src/docs/concepts-extended-data/user-extended-data/index.md
- src/docs/concepts-listings/how-the-search-works/index.md
- src/docs/concepts-listings/listings-overview/index.md
Add resource specific extended data articles
> Add resource specific extended data articles

- src/docs/concepts-api-sdk/rate-limiting/index.md
Add an article on how rate limiting is done in Flex and how it can be handled gracefully.
> Add concepts article on handling rate limits

- src/components/MainLayout.js
- src/components/VersionBanner/VersionBanner.js
- src/components/Warning.js
- src/components/WarningIcon.js
- src/components/index.js
- vercel.json
Don't merge before release of combined template
> Legacy docs banner

- src/docs/references/extended-data/index.md
Listings currently have no protected data, so remove reference to listing in the reference.
> Remove mention of listing from protected data reference

- src/docs/the-new-sharetribe/tutorial-listing-search/index.md
Add a step to allow for keyword filter search, even if location search is enabled.
> Update TNS tutorial

- src/docs/the-new-sharetribe/the-new-sharetribe-analytics/how-to-configure-google-search-console/index.md
- src/docs/the-new-sharetribe/the-new-sharetribe-analytics/how-to-track-your-marketplace-traffic-with-an-analytics-service/index.md
- Analytics services (which described Google Analytics, the only service supported at this point)
- Google Search Console
> Add two articles to the TNS Help Center

- src/docs/howto-events/set-up-and-use-zapier/index.md
Deflexed the Templates, removed outdated ones, added a new one, minor copy text fixes.
> Update Zapier templates

- src/docs/howto-content/article-blog/index.md
- src/docs/howto-migrations/migrating-from-outside-sharetribe/index.md
- src/docs/introduction/getting-started-with-ftw-daily/index.md
- src/ui-texts.json
- Update content page count
- Add anonymisation details to migration guide
- Fix landing page wording
- Fix numbering and indentation in template getting started guide
> Fix small issues

- src/docs/howto-messaging/set-up-outgoing-email-settings/index.md
Console UI https://github.com/sharetribe/sharetribe-custom/pull/3153
> Add instructions abotu DMARC

- src/docs/howto-messaging/set-up-outgoing-email-settings/index.md
- src/docs/tutorial-branding/deploy-to-render/index.md
- Use the term "staging environment" about the deployed application
- Specify when to use client credentials from Dev environment and when to use ones from Test environment
> Clarify deploy-to-render article re: environments

- src/docs/ftw-configuration/how-to-set-up-currency-in-ftw/index.md
- src/docs/references/extended-data/index.md
- Add helper update to currency change instructions
- Add mention of extended data max size in references
> Docs fixes

- src/docs/howto-payments/how-to-integrate-3rd-party-payment-gateway/index.md
> Fix comment syntax

- src/docs/concepts-listings/listings-overview/index.md
Add mention of discard draft endpoint and expand on listing creation and closing logic.
> Update listings overview article

- src/components/ArticlePage/Footer.js
> De-Flex the article footer

- src/docs/howto-users-and-authentication/setup-oidc-proxy/index.md
Update the OIDC proxy article to align with most recent AuthenticationPage.
> Update OIDC proxy article

- src/docs/concepts-extended-data/user-extended-data/index.md
- src/docs/howto-users-and-authentication/implement-delete-user/index.md
> Add mention of differentiating user type experience in Console
