gatsby-config.js
gatsby-node.js
src/pages/operator-guides.js
src/ui-texts.json

Creates "operator-guides" category, which is not visible on navigation or sitemap.xml (and therefore it's hopefully not visible in Algolia-indexed search)
And this also adds index page for the aforementioned category.

Add invisible category: operator-guides

---

src/docs/cookbook-data-model/extend-listing-data-in-ftw/index.md
src/docs/cookbook-design/customize-image-sizes/index.md
src/docs/ftw-search/how-to-use-google-maps-in-ftw/index.md
src/docs/ftw-styling/how-to-add-static-pages-in-ftw/index.md
src/docs/ftw-styling/how-to-customize-ftw-styles/index.md
src/docs/introduction/getting-started-with-ftw-daily/index.md
src/docs/tutorial-branding/add-faq-page/index.md
src/docs/tutorial-branding/change-image-assets/index.md
src/docs/tutorial-branding/change-logo/index.md
src/docs/tutorial-branding/first-edit/index.md
src/docs/tutorial-extended-data/show-extended-data/index.md
src/docs/tutorial-transaction-process/customize-pricing/index.md
src/docs/tutorial-transaction-process/use-protected-data-in-emails/index.md

- Renamed component stylesheets: `*.css` => `*.module.css`
- Removed **marketplaceIndex.css**
- Removed **marketplaceFonts.css**
- Removed **marketplace.css**
- New **src/styles/marketplaceDefaults.css**
- New **src/styles/propertySets.css**
- How to use vanilla CSS

Update docs to match sharetribe-scripts v4 change

---

static/sample-template-context.json

line-items is deprecated, tx-line-items should be used instead and it's confusing to have line-items in the docs.

Remove line-items from sample, tx-line-items is correct

---

src/docs/cookbook-social-logins-and-sso/setup-oidc-proxy/index.md
static/tutorial-assets/linkedin.js

Update OIDC proxy cookbook to match new `/.well-known` path in FTW and add other improvements to the OIDC proxy implementation experience.

Update linkedin proxy cookbook

---

src/docs/cookbook-social-logins-and-sso/setup-oidc-proxy/index.md
static/tutorial-assets/linkedin.js

Linkedin specific varibale names enforce the idea of creating a distinct
IdP for each login service.

Update OIDC proxy en variable names

---

src/docs/ftw-routing/how-code-splitting-works-in-ftw/index.md
src/docs/ftw-routing/how-routing-works-in-ftw/index.md
src/docs/ftw-styling/how-to-customize-ftw-styles/index.md
src/docs/tutorial-branding/change-logo/index.md
src/docs/tutorial-branding/first-edit/index.md

link: `[code-splitting](/ftw-routing/how-code-splitting-works-in-ftw/)`
In the last article, I also shortened the sub headings:

Update articles: How routing works & code splitting & first edit

---

docs/README.md
src/docs/ftw-introduction/01-how-to-customize-ftw/index.md
src/docs/operator-guides/hiring-developer-to-build-your-flex-marketplace/index.md
src/docs/tutorial-branding/deploy-to-heroku/index.md
src/docs/tutorial/introduction/index.md

Github has changed default branch naming convention (master -> main) and also its own docs.
This update recommends that after cloning user:
1. changes branch name locally
```shell
git branch -m master main
```
2. pushes the local default branch into newly created empty repo as **main**
```shell
git push -u origin main
```

Update default branch naming instructions

---

src/docs/operator-guides/console-overview/index.md

Adds "Events" and short description of the page about it in the "Understanding Console" article.

Add one section about Events to an operator guide

---

src/docs/background/off-session-payments/index.md
src/docs/background/transaction-process/index.md

Add details about delayed transitions into articles handling off-session payments and transaction process.

Add info about only using single delayed transition to Docs

---

src/docs/background/features/index.md
src/docs/background/how-sca-works/index.md
src/docs/background/using-stored-payment-cards/index.md
src/docs/cookbook-transaction-process/change-transaction-process-in-ftw/index.md
src/docs/flex-cli/getting-started-with-flex-cli/index.md
src/docs/ftw-introduction/ftw-hourly/index.md
src/docs/references/availability/index.md

- Update obsolete 'FTW-time' references into 'FTW-hourly' references
- Add instructions on how to enable and disable listing approval functionality in Flex CLI.

Add listing approval instructions and update FTW-time to FTW-hourly

---

src/docs/ftw-introduction/ftw-hourly/index.md

The FTW-hourly introduction section had typos and unclarities in the section dealing with changing from single listing mode to multiple listing mode. Fix the typos and clarify the instructions.

Fix typos in FTW-hourly introduction

---

src/docs/background/commissions-and-monetizing-your-platform/index.md
src/docs/cookbook-transaction-process/enable-time-based-bookings/index.md
src/docs/flex-cli/edit-transaction-process-with-flex-cli/index.md
src/docs/references/transaction-process-format/index.md
src/docs/tutorial-transaction-process/create-transaction-process/index.md
src/docs/tutorial-transaction-process/customize-pricing/index.md

Some Docs articles referenced deprecated transaction process actions for setting commissions in code examples. This PR replaces those references with up-to-date examples.

Remove references to deprecated commission actions

---

src/docs/cookbook-payments/set-up-and-use-stripe/index.md

FTW does not support all countries where Stripe Custom Connect accounts are available. This PR adds information on the reasons why Brazil, India and Hungary aren't supported, so users can determine whether adding them through custom development is worth the effort for them.

Mention problematic Stripe countries in setup cookbook

---

src/docs/operator-guides/migrating-from-outside-sharetribe/index.md

Improve operator guide documentation on the Intermediary format
- Add code examples to illustrate the text throughout
- Add mention that user performs the extract and transform steps of migration, and Sharetribe loads the data into Flex
- Expand explanations of referencing and aliases in Intermediary
- Add detailed validation schemas with `required` / `optional` information for each resource available for migration
- Add explanations of value types used in Intermediary
- Add mentions of data sharing methods as well as using a representative subset of the data for test migrations

Add first draft of migration docs improvements

---

src/components/Topbar/Search.js

Update Docsearch API credentials. Adds a new config param: `appId`.

Update Docsearch API credentials

---

src/docs/ftw-hosting/how-to-deploy-ftw-to-production/index.md
src/docs/tutorial-branding/deploy-to-heroku/index.md

Heroku is having security issues, so add a warning in relevant articles that we're aware of the situation and looking into alternatives.

Add Heroku related warnings to relevant articles

---

src/docs/concepts-api-sdk/api-reference/index.md
src/docs/concepts-development/translations/index.md
src/docs/references/assets/index.md

Based on #560 and targeting that branch, but if that documentation needs more time, we can adjust this.
There may be other places in the docs that list all Flex APIs, that I didn't find. Those might look off, now that we're adding a new API, but we can fix them as we notice them. Let me know, if you spot already some places that would feel off!

Marketplace assets

---

src/docs/operator-guides/concepts/index.md
src/docs/references/events/index.md

- Remove the mention of planned webhooks
- Mention events in the context of webhooks and vice versa

Connect mentions of webhooks with events

---

src/components/ArticlePage/ArticlePage.js
src/components/GlobalStyle.js
src/components/Topbar/Search.js
src/config-site-structure.js
src/docs/concepts-users-and-authentication/users-and-authentication-in-flex/index.md
src/docs/ftw-styling/how-to-customize-ftw-styles/index.md
src/docs/howto-users-and-authentication/implement-delete-user/cookbook-assets/DeleteAccountForm.module.css
src/docs/introduction/getting-started-with-ftw-daily/index.md
src/docs/references/events/index.md
src/docs/tutorial-branding/change-image-assets/index.md
src/docs/tutorial-branding/first-edit/index.md
src/pages/concepts.js
src/pages/design-toolkit.js
src/pages/ftw.js
src/pages/how-to.js
src/pages/introduction.js
src/pages/operator-guides.js
src/pages/references.js
src/pages/tutorial.js

propertySets.css will be removed from templates. This updates all the docs that mention it.
In addition, I called `yarn run format`.

Sharetribe scripts v6 (propertySets.css is removed)

---

src/docs/operator-guides/how-to-use-microcopy-editor/index.md

Fix a Nemesis redirect from a link without the final trailing slash to one with the slash.

Remove-redirect

---

src/docs/howto-search/manage-search-schemas-with-flex-cli/index.md

Search schemas with default values have not been documented. This change adds a paragraph in the relevant how-to article on adding a search schema with a default value set.

Add paragraph of search schema default value

---

src/docs/concepts-pricing-and-commissions/commissions-and-monetizing-your-platform/index.md
src/docs/concepts-pricing-and-commissions/pricing/index.md
src/docs/concepts-transactions/privileged-transitions/index.md
src/docs/howto-payments/customize-pricing/index.md

Deploy preview in link is no longer available. Remove references to link.

Remove references to deprecated pricing articles

---

src/docs/howto-users-and-authentication/setup-oidc-proxy/index.md

The FTW as OIDC proxy setup sometimes causes confusion in terms of what, exactly, needs to be the IdP URL. Improve formatting and add an extra explanation to clarify that IdP URL points to FTW, not the IdP being wrapped.

Clarify IDP URL explanation in FTW OIDC proxy article

---

src/docs/references/transaction-process-format/index.md

Clarify that delayed notifications will be cancelled if the transaction moves forward. This was mentioned already, but I added it now to a couple more places.

Improve documentation of delayed notifications

---

src/components/Sidebar/Sidebar.js

Changes [scrollIntoView()](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView) option "block" to "nearest" instead of "center". Using the center option forced the menu bar to scroll too much in links positioned towards the end of the navigation, forcing the main window to scroll in addition to the navigation bar. However, this approach sometimes positions the active link in the scroll bar at the very bottom of the browser window. From a UI standpoint, this is a bit of a compromise.
I looked into writing some custom logic by calculating the window height and the positioning of the current element in relationship to the containing element, but it started to get unnecessarily complex, and I encountered a bunch of annoying edge cases. I'm not sure if it's worth …

fix autoscroll bug

---

src/docs/concepts-messages/email-notifications/index.md
src/docs/concepts-payments/payments-overview/index.md
src/docs/howto-listing/seats/index.md
src/docs/introduction/getting-started-with-flex-cli/index.md
src/docs/references/assets/index.md
src/docs/references/email-templates/index.md

This PR updates the headings for default assets to correspond to the headings where those assets are modified in Console (in [/references/assets/index.md](https://github.com/sharetribe/flex-docs/pull/869/files#diff-355989deba881861dc38945d9e84b18b50d92b7e32c9d96753d38649b839d3ea)). In addition, some files were not formatted according to `yarn run format`, so updating those in this PR as well.

Update assets structure and fix formatting
